### ISSUE TITLE
Camunda BPM Platform wildfly + JSON Logging

### ISSUE THREAD

**Issue by joaopalma5** [DigitalState/camunda-json-logging#5]
Hello,

It's possible run this plugin using Camunda BPM Platform Wildfly ? How?

Best Regards

**Comment by StephenOTT** [comment]
Hi. You would have to duplicate the pattern for wildfly setup. Only the tomcat pattern was developed at the moment.  

I would say it would be much easier for you to take a default Camunda spring boot app. Add in Json logging and package it as a WAR and deploy that to wildfly.

**Comment by joaopalma5** [comment]
@StephenOTT, Please you can explain me better how add json logging in camunda spring boot app?

Thanks for your help

**Comment by StephenOTT** [comment]
You add it like any other spring boot application. (Such as adding it the logback configuration and required deps).  See springboot's logging docs.

**Comment by joaopalma5** [comment]
@StephenOTT this plugin ( https://github.com/kifj/camunda-wildfly-logging ) can log in JSON but I can't find how to enable when a activity is started or finished
